-- Отключение всех ограничений внешних ключей временно
SET session_replication_role = 'replica';

-- Удаление таблиц
DROP TABLE IF EXISTS BookBranch CASCADE;
DROP TABLE IF EXISTS CriticApplications CASCADE;
DROP TABLE IF EXISTS Tags CASCADE;
DROP TABLE IF EXISTS EBooks CASCADE;
DROP TABLE IF EXISTS ReadingRooms CASCADE;
DROP TABLE IF EXISTS LostBooks CASCADE;
DROP TABLE IF EXISTS Complaints CASCADE;
DROP TABLE IF EXISTS BookReviewsVotes CASCADE;
DROP TABLE IF EXISTS WishList CASCADE;
DROP TABLE IF EXISTS Reviews CASCADE;
DROP TABLE IF EXISTS Reservations CASCADE;
DROP TABLE IF EXISTS Fines CASCADE;
DROP TABLE IF EXISTS BookDistribution CASCADE;
DROP TABLE IF EXISTS Favorites CASCADE;
DROP TABLE IF EXISTS Notifications CASCADE;
DROP TABLE IF EXISTS Events CASCADE;
DROP TABLE IF EXISTS Attendance CASCADE;
DROP TABLE IF EXISTS LibraryBranches CASCADE;
DROP TABLE IF EXISTS Feedbacks CASCADE;
DROP TABLE IF EXISTS UserActivity CASCADE;
DROP TABLE IF EXISTS BookCategories CASCADE;
DROP TABLE IF EXISTS Books CASCADE;
DROP TABLE IF EXISTS Publishers CASCADE;
DROP TABLE IF EXISTS Categories CASCADE;
DROP TABLE IF EXISTS Authors CASCADE;
DROP TABLE IF EXISTS Profiles CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Roles CASCADE;
DROP TABLE IF EXISTS FeedbackRatings CASCADE;

-- Восстановление ограничений внешних ключей
SET session_replication_role = 'origin';
